{
 "title": "mubench-istio",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "delta", "query": "1m" },
   { "name": "ns", "query": "istio-ingress|default" },
   { "name": "istio_ingress_prometheus_label", "query": "istio-ingressgateway" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (destination_service_name) (rate(istio_response_bytes_count{destination_service_name=~\"s[0-9*]\",reporter=\"destination\",response_code=\"200\",namespace=~\"$ns\"}[$delta]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Service delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by (destination_service_name) (rate(istio_request_duration_milliseconds_sum{namespace=~\"$ns\",destination_service_name=~\"s[0-9]*\",reporter=\"source\",response_code=\"200\"}[$delta]))) / (sum by (destination_service_name) (rate(istio_requests_total{namespace=~\"$ns\",destination_service_name=~\"s[0-9]*\",reporter=\"source\",response_code=\"200\"}[$delta])))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Service traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum by (destination_workload) (rate(istio_response_bytes_sum{source_workload=~\"$istio_ingress_prometheus_label|s[0-9]*.\",destination_workload=~\"s[0-9].*\",reporter=\"destination\",response_code=\"200\",namespace=~\"$ns\"}[$delta])*8/1e6)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "P90 delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (destination_app,le) (rate(istio_request_duration_milliseconds_bucket{namespace=~\"$ns\",reporter=\"source\"}[$delta])))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{namespace=~\"$ns\",pod=~\"s[0-9].*\",container!=\"istio-proxy\",container!=\"\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (sum by (container) (container_memory_usage_bytes{namespace=~\"$ns\",pod=~\"s[0-9].*\",container!=\"istio-proxy\",container!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_blkio_device_usage_total{namespace=~\"$ns\",pod=~\"s[0-9].*\",container!=\"istio-proxy\",container!=\"\"}[$delta]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service replicas",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) (kube_deployment_status_replicas{namespace=~\"$ns\",deployment=~\"s[0-9].*\",container!=\"istio-proxy\",container!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "µbench internal delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (app_name) (increase(mub_internal_processing_latency_milliseconds_sum{namespace=~\"$ns\"}[2m])) / sum by (app_name) (increase(mub_internal_processing_latency_milliseconds_count{namespace=~\"$ns\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "µbench external delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (app_name) (increase(mub_external_processing_latency_milliseconds_sum{namespace=~\"$ns\"}[2m])) / sum by (app_name) (increase(mub_external_processing_latency_milliseconds_count{namespace=~\"$ns\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "call frequency per user request",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (destination_service_name) (rate(istio_response_bytes_count{destination_service_name=~\"s[0-9*]\",reporter=\"destination\",response_code=\"200\",namespace=~\"$ns\"}[$delta])) / scalar(sum by (destination_service_name) (rate(istio_response_bytes_count{destination_service_name=~\"s[0*]\",reporter=\"destination\",response_code=\"200\", namespace=~\"$ns\"}[$delta])))",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}