FROM python:slim

RUN apt update
RUN apt install -y screen
COPY requirements.txt /app/

WORKDIR /app

RUN pip install -r requirements.txt

RUN apt -y install vim ssh iproute2 vim curl

COPY id_rsa.pub /root/.ssh/authorized_keys

EXPOSE 22
EXPOSE 8080
EXPOSE 51313

COPY CellController.py ExternalServiceExecutor.py InternalServiceExecutor.py mub.proto mub_pb2.py \
mub_pb2_grpc.py start.sh ./

CMD [ "/bin/bash", "-c", "service ssh restart && /bin/bash /app/start.sh"]

